### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by gmathieu** [segmentio/analytics-next#303]
Hello,

Leveraging the example in the README raises the following error with v1.30.0:

![image](https://user-images.githubusercontent.com/7855/139306172-eb4782fb-9737-4d62-9ac8-720bcfab76f2.png)

It looks like `process.env` variables aren't being replaced during the `pkg` build: https://github.com/segmentio/analytics-next/blob/35bd0501a9130645802e953b03ec5414e83a1138/webpack.config.js#L16-L21

Great job on the new library! I'm working on replacing our use of https://github.com/segmentio/analytics.js-core with it. 

Thanks

Tip: you might also want to add `files: ["dist/", "src/"]` to `package.json` so only runtime files are published to NPM (see [files](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files)) as opposed to the whole repo
![image](https://user-images.githubusercontent.com/7855/139308233-d1a74a25-a621-44cc-a6f9-6c2ce39b50c1.png)

**Comment by danieljackins** [comment]
Hey @gmathieu thanks for opening the issue!

I'm having trouble replicating this, do you have any further info or replication steps? (following the example in the README works for me)

**Comment by gmathieu** [comment]
Hi @danieljackins,

It's a tricky one. Here's a sandbox with the error https://codesandbox.io/s/webpack-segment-analytics-next-5y33h?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/7855/139508209-5fcbc561-bd49-47c1-b700-35953d175c73.png)
Note: Codesandbox doesn't capture these types of errors so you'll have to open the native console to see it.

Here's what I've been able to gather:
- this only affects `dist/pkg` because it is compiled using `tsc`. As opposed to `dist/umd` which is bundled using Webpack
  - For example, `process.env.VERSION` should be replaced with `"1.30.0"` in `dist/pkg/plugins/segmentio/normalize.js`
- #305 partially fixe the issue for bundlers that leverage CommonJS but ESM will likely be affected
- big assumption: the e2e tests run a local web server which leverages the same Webpack config. Because that config defines the same `EnvironmentPlugin`, all `process.env.*` were replaced with proper values

I hope this helps 🤞

**Comment by danieljackins** [comment]
Hey @gmathieu sorry for the delay and thanks for the PR. We addressed this issue with https://github.com/segmentio/analytics-next/pull/331, as we wanted to avoid adding another bundler.

**Comment by BorePlusPlus** [comment]
Nice one @danieljackins  🎉

How long does it usually take for a fix like this to make it into a release?

**Comment by pooyaj** [comment]
`1.32.0` is released 💥

**Comment by gmathieu** [comment]
Hi @danieljackins, thanks for tackling this. Unfortunately, the problem is only partially solved since `process.env` is still used in https://github.com/segmentio/analytics-next/blob/505197da44558ee565a0fb25d78599c0ce4ffb28/src/browser.ts#L3-L16 or if someone were to provide legacy settings https://github.com/segmentio/analytics-next/blob/505197da44558ee565a0fb25d78599c0ce4ffb28/src/browser.ts#L80-L86.

@pooyaj v1.32.0 appears to be broken. Somehow `dist/cjs` and `dist/pkg` ended up with an extra `src/` directory so `main`, `module`, and `types` from `package.json` are no longer pointing to the right path.

Sorry to be the bearer of bad news and thanks for the help.

**Comment by pooyaj** [comment]
Oh, thanks for flagging this, and sorry for publishing the broken package. Looks like we need to iron out few things in the coming week before publishing the fix again.

**Comment by BorePlusPlus** [comment]
Hey, @pooyaj 👋  
Am I correct in assuming that #336 addresses the issues raised by @gmathieu ?

I that's the case could we see a bugfix release soon? Something like 1.32.1?

**Comment by pooyaj** [comment]
@BorePlusPlus Yes, almost, except the last issue raised by Guillaume to remove the last few uses of `process.env`. We will quickly address that last piece and hopefully release.

**Comment by gmathieu** [comment]
@chrisradek I see you're working on https://github.com/segmentio/analytics-next/pull/343. Although this solution resolves the `process.env` issue, the runtime override of `__webpack_public_path__` will break any consumers of `@segment/analytics-next` that use Webpack to build their app (since their application doesn't point to `__webpack_public_path__ = cdn + '/analytics-next/bundles/'`).

Moving that logic out of `src/browser.ts` should do the trick. The new file would look something like:

```ts
// browser-umd.ts
import { getCDN } from './lib/parse-cdn'

if (process.env.ASSET_PATH) {
  if (process.env.ASSET_PATH === '/dist/umd/') {
    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/camelcase
    __webpack_public_path__ = '/dist/umd/'
  } else {
    const cdn = window.analytics?._cdn ?? getCDN()
    if (window.analytics) window.analytics._cdn = cdn

    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/camelcase
    __webpack_public_path__ = cdn + '/analytics-next/bundles/'
  }
}

import './browser.ts'
```

## Food for thought:

I don't fully understand what this UMD bundle is used for https://github.com/segmentio/analytics-next/blob/10ddd6148504a8e9809534879a3da852a793baa4/webpack.config.js#L30-L36 or why consumers of `src/browser.ts` would need to run the following side effect https://github.com/segmentio/analytics-next/blob/10ddd6148504a8e9809534879a3da852a793baa4/src/browser.ts#L9-L10. Maybe this logic is only needed in the `src/standalone.ts` which consumers of `@segment/analytics-next` shouldn't use. Maybe `tsc` should only build files imported by `src/index.ts` as opposed to including the whole `src` directory. This would require some refactor as some global type definitions are only defined in `src/standalone-analytics.ts`.

Thanks everyone for bearing with me.

**Comment by chrisradek** [comment]
> Although this solution resolves the process.env issue, the runtime override of __webpack_public_path__ will break any consumers of @segment/analytics-next that use Webpack to build their app (since their application doesn't point to __webpack_public_path__ = cdn + '/analytics-next/bundles/').

So it sounds like there are 2 issues.

1. `process` is undefined unless you've configured your bundler to inject them.
2. When doing you're own bundling, if you are setting the `ASSET_PATH` environment variable we end up overriding the `__webpack_public_path__`.

It looks like our own webpack bundle was removing the ASSET_PATH codepath, but my change in #343 undoes that. Will need to dig into how our webpack config was removing that codepath. Re-opening this issue since we're still working on it.

**Comment by gmathieu** [comment]
@chrisradek correct on both. I don't know how likely people will set `process.env.ASSET_PATH` in their own application but it's possible.

> It looks like our own webpack bundle was removing the ASSET_PATH codepath, but my change in #343 undoes that.

Webpack uses `webpack.EnvironmentPlugin` to replace `process.env.*` with the value defined in the config. The code then becomes something like:

```ts
if ("https://cdn.segment.com/analytics-next/bundles/") {
  if ("https://cdn.segment.com/analytics-next/bundles/" === '/dist/umd/') {
    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/camelcase
    __webpack_public_path__ = '/dist/umd/'
  } else {
    const cdn = window.analytics?._cdn ?? getCDN()
    if (window.analytics) window.analytics._cdn = cdn

    // @ts-ignore
    // eslint-disable-next-line @typescript-eslint/camelcase
    __webpack_public_path__ = cdn + '/analytics-next/bundles/'
  }
}
```
The minifier plugin (Terser in this case) understands that the first two conditions are always true and false respectively so it considers the code as "dead" and removes it. We end up with:
```ts
const cdn = window.analytics?._cdn ?? getCDN()
if (window.analytics) window.analytics._cdn = cdn

// @ts-ignore
// eslint-disable-next-line @typescript-eslint/camelcase
__webpack_public_path__ = cdn + '/analytics-next/bundles/'
```

I'm sorry it took 3 PRs (#331, #336, and now #343) to get to where we are today. Maybe it's an indication that the problem is with the bundler and not the code itself. @danieljackins I totally empathize with the reluctance to replace tsc with another bundler like Rollup. I do think the ability to inject global variables and removing the resulting dead code is well worth it (let's not forget about the ability to inject test logic such as [this](https://github.com/segmentio/analytics-next/blob/10ddd6148504a8e9809534879a3da852a793baa4/src/browser.ts#L82)). 

Let me know if I can help in any way.

**Comment by chrisradek** [comment]
@pooyaj gave me a history lesson on the `ASSET_PATH` codepath. My understanding now is that it's only needed for the UMD bundle (which is built for the version we host), and not for the CJS/module builds. So I think your earlier suggestion of having that logic in a umd-specific file is the right direction for now.

I really appreciate the digging into this issue you've done, thank you!
